<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VAIO" ignored="0" name="AddNewPayee" tests="5" failures="1" timestamp="2019-12-01T15:56:18 IST" time="66.907" errors="0">
  <testcase name="addNewPayee" time="2.734" classname="tests.AddNewPayee"/>
  <testcase name="addNewPayee" time="0.189" classname="tests.AddNewPayee"/>
  <testcase name="addNewPayee" time="0.124" classname="tests.AddNewPayee"/>
  <testcase name="addNewPayee" time="0.111" classname="tests.AddNewPayee"/>
  <testcase name="test02" time="0.002" classname="tests.AddNewPayee">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at tests.AddNewPayee.test02(AddNewPayee.java:58)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test02 -->
</testsuite> <!-- AddNewPayee -->
